Repository nbcamp-a3/my-best-project, pull requests merged in 2023-11, with the labels that each got.

#6 feat: 초기 프로젝트 설정 추가
  src/GlobalStyle.js
  src/components/Footer/index.js
  src/components/Footer/styles.js
  src/components/Header/Header.jsx
  src/components/Header/styles.js
  src/components/Layout/Layout.jsx
  src/components/Layout/styles.js
  src/constants/colors.js
Labels: 설정, 수정

#8 feat: 라우팅 설정
  src/Router.js
  src/pages/AllBoard.jsx
  src/pages/BoardDetail.jsx
  src/pages/MyPage.jsx
  src/pages/NewBoard.jsx
  src/pages/index.js
Labels: 기능

#9 feat: 전체 레이아웃 수정 (#2)
  src/components/Layout/Layout.jsx
  src/components/Layout/styles.js
Labels: UI

#10 feat: 상세페이지 UI 구성 (#1)
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/styles.js
  src/pages/BoardDetail.jsx
Labels: UI, 수정

#14 feat: SNS 로그인, 로그아웃 기능
  src/config/firebase.js
  src/hooks/useAuth.js
  src/redux/config/configStore.js
  src/redux/modules/User.js
Labels: 기능

#17 상세페이지 styled-components 변경
  src/components/BoardDetail/styles.js
Labels: 수정

#18 feat: 로그인 여부에 따라 페이지 리다이렉트
  src/App.jsx
  src/Router.js
  src/components/LoadingScreen/LoadingScreen.jsx
  src/config/firebase.js
  src/index.js
  src/pages/ProtectedRoute.jsx
  src/pages/index.js
Labels: 기능

#22 feat:메인페이지 반응형 UI 구현 & 디테일 페이지와 연결
  src/components/Footer/styles.js
  src/components/Header/Header.jsx
  src/components/Header/styles.js
  src/components/Home/ContexntBox.jsx
  src/components/Home/HomeContainer.jsx
  src/components/Home/style.js
Labels: UI

#23 feat: 글쓰기 상세페이지 UI 구성
  src/components/NewBoard/styles.js
  src/pages/NewBoard.jsx
Labels: UI, 수정

#21 feat: 과제게시판 UI 및 Route, Redux 구현
  src/components/AllBoard/AllBoardCard.jsx
  src/components/AllBoard/AllBoardIndex.jsx
  src/components/AllBoard/AllBoardList.jsx
  src/components/AllBoard/styles.js
  src/mock/allBoards.js
  src/pages/AllBoard.jsx
  src/redux/config/configStore.js
  src/redux/modules/User.js
  src/redux/modules/selectedCategory.js
Labels: UI, 기능

#26 feat: 글쓰기 페이지 기능 구현
  src/App.jsx
  src/components/NewBoard/styles.js
  src/config/firebase.js
  src/pages/NewBoard.jsx
Labels: 기능, 수정

#30 feat: 상세페이지 UI 수정 및 게시판 Firebase 연동
  src/components/AllBoard/AllBoardEmptyCard.jsx
  src/components/AllBoard/AllBoardIndex.jsx
  src/components/AllBoard/AllBoardList.jsx
  src/components/AllBoard/styles.js
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/styles.js
  src/redux/config/configStore.js
  src/redux/modules/boards.js
Labels: 기능, 수정

#31 feat: 로그인 모달창 UI
  src/components/Auth/AuthModal.jsx
  src/components/Auth/AuthStartScreen.jsx
  src/components/Auth/EmailLoginScreen.jsx
  src/components/Auth/SignUpScreen.jsx
  src/components/Auth/styles.js
  src/components/Header/Header.jsx
Labels: UI

#28 feat: style 수정 및 confirm 추가
  src/components/NewBoard/styles.js
  src/pages/NewBoard.jsx
Labels: 기능, 수정

#32 feat: 로그인 모달창 UI
  src/components/Auth/AuthModal.jsx
  src/components/Auth/AuthStartScreen.jsx
  src/components/Auth/EmailLoginScreen.jsx
  src/components/Auth/SignUpScreen.jsx
Labels: UI

#34 feat: 글쓰기 사진 첨부 기능
  package.json
  src/components/AllBoard/AllBoardIndex.jsx
  src/components/NewBoard/styles.js
  src/config/firebase.js
  src/pages/NewBoard.jsx
  src/redux/modules/boards.js
  yarn.lock
Labels: 기능

#35 feat: default image 추가
  src/pages/NewBoard.jsx
Labels: 기능

#37 feat: CURD 중 R, D구현
  src/components/AllBoard/AllBoardCard.jsx
  src/components/AllBoard/AllBoardList.jsx
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/styles.js
  src/pages/BoardDetail.jsx
Labels: 기능

#38 feat: 마이페이지 모달UI, 모달 토글 기능
  src/components/Header/Header.jsx
  src/components/Header/styles.js
  src/components/Headermodal/Headermodal.jsx
  src/components/Headermodal/style.js
Labels: UI, 기능

#42 feat: 삭제 시 유저 검사
  src/Router.js
  src/components/AllBoard/AllBoardList.jsx
  src/components/BoardDetail/BoardDetailContent.jsx
  src/pages/ProtectedRoute.jsx
Labels: 기능

#43 feat: github 주소 등록 추가 및 style 수정
  src/components/NewBoard/styles.js
  src/pages/NewBoard.jsx
  src/redux/modules/boards.js
Labels: 기능, 수정

#46 feat: 회원가입, 로그인 구현
  src/components/Auth/AuthStartScreen.jsx
  src/components/Auth/EmailLoginScreen.jsx
  src/components/Auth/SignUpScreen.jsx
  src/components/Auth/styles.js
  src/config/errors.js
  src/config/firebase.js
Labels: 기능

#47 Feature/main 메인페이지 모달, 데이터 추가 수정
  src/components/Header/Header.jsx
  src/components/Header/styles.js
  src/components/Headermodal/Headermodal.jsx
  src/components/Headermodal/style.js
  src/components/Home/ContentContainer.jsx
  src/components/Home/ContexntBox.jsx
  src/components/Home/HomeContainer.jsx
  src/components/Home/MainContent.jsx
  src/components/Home/style.js
Labels: UI, 기능, 수정

#51 feat: 콘텐츠 박스 이미지 고정 & 내림차순 4개만 출력
  src/components/Header/Header.jsx
  src/components/Header/styles.js
  src/components/Headermodal/Headermodal.jsx
  src/components/Headermodal/style.js
  src/components/Home/ContentContainer.jsx
  src/components/Home/style.js
Labels: 리팩토링, 수정

#49 feat: 수정 페이지 기능 구현
  src/Router.js
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/styles.js
  src/components/EditBoard/EditBoardContent.jsx
  src/components/NewBoard/NewBoardContent.jsx
  src/components/NewBoard/styles.js
  src/pages/EditBoard.jsx
  src/pages/NewBoard.jsx
  src/pages/index.js
Labels: 기능, 수정

#53 style: Input 아이콘 추가 회원가입 기본 이미지 설정
  src/components/Auth/EmailLoginScreen.jsx
  src/components/Auth/SignUpScreen.jsx
  src/components/Auth/styles.js
Labels: 수정

#56 feat: DetailPage style 수정 및 MyPage 퍼블리싱, 기술구현
  src/components/AllBoard/styles.js
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/styles.js
  src/components/MyPage/MyPage.jsx
  src/components/MyPage/style.js
  src/pages/MyPage.jsx
Labels: UI, 기능, 수정

#55 feat: style 수정 및 github링크, UI 수정
  public/favicon.ico
  src/components/AllBoard/AllBoardList.jsx
  src/components/AllBoard/styles.js
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/styles.js
  src/components/EditBoard/EditBoardContent.jsx
  src/components/NewBoard/NewBoardContent.jsx
Labels: UI, 기능, 수정

#58 feat: myPage 퍼블리싱 및 기술구현
  src/Router.js
  src/components/AllBoard/AllBoardCard.jsx
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/MyPage/EditProfiles.jsx
  src/components/MyPage/MyPages.jsx
  src/components/MyPage/style.js
  src/components/NewBoard/NewBoardContent.jsx
  src/pages/EditProfile.jsx
  src/pages/MyPage.jsx
Labels: UI, 기능

#60 fix: 마이 페이지 프로필 수정 url에서 로그아웃하면 alert창 두 번 뜨는 문제
  src/pages/ProtectedRoute.jsx
Labels: 수정

#61 feat: 댓글 기능 구현
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/Comments.jsx
  src/components/BoardDetail/styles.js
  src/pages/BoardDetail.jsx
Labels: UI, 기능, 수정

#64 feat: 글쓰기 에디터 사진 firebase 업로드
  src/components/BoardEditor/BoardEditor.jsx
Labels: 기능

#66 feat: 좋아요 기능&nav바 라우팅 (#65)
  src/components/AllBoard/AllBoardCard.jsx
  src/components/AllBoard/styles.js
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardDetail/styles.js
  src/components/Header/Header.jsx
  src/components/Home/style.js
  src/components/NewBoard/NewBoardContent.jsx
  src/redux/modules/likedusers.js
Labels: 기능, 수정

#68 feat: 전체 스타일링 수정
  src/components/AllBoard/AllBoardCard.jsx
  src/components/BoardDetail/BoardDetailContent.jsx
  src/components/BoardEditor/BoardEditor.jsx
  src/components/EditBoard/EditBoardContent.jsx
  src/components/Home/ContexntBox.jsx
  src/components/Home/MainContent.jsx
  src/components/Home/style.js
  src/components/NewBoard/NewBoardContent.jsx
  src/components/NewBoard/styles.js
Labels: UI, 리팩토링, 수정
